button_signUpHeader = "xpath=//button[text()='Sign up']"
inputField_firstName = "xpath=//input[@id='first-name']"
inputField_lastName = "xpath=//input[@id='last-name']"
inputField_middleName = "xpath=//input[@id='middle-name']"
inputField_email = "xpath=//input[@id='email']"
inputField_contactNumber = "xpath=//input[@id='contact-number']"
inputField_company = "xpath=//input[@id='company']"
inputField_companyAddress = "xpath=//input[@id='company-address']"
inputField_password = "xpath=//input[@id='password']"
inputField_comfirmPassword = "xpath=//input[@id='confirm-password']"
button_signUpRegistration = "xpath=//button[@type='submit'][text()='Sign Up']"